GH-74 Add buttons to socials for projects in project tab. Remove projects EternalRTP and EternalCheck
EternalCodeTeam/EternalCode-WWW pull request #74
Opened 2023-03-02 22:40 UTC by Embrejs

And change name for CitralFlo

2023-03-03 17:37 UTC, vLuckyyy requested changes
Dodatkowo, strona nie jest responsywna.
Ponadto fajnie gdybyś zrobił tak aby pojedyńcze ikony były wyśrodkowane:
![image](https://user-images.githubusercontent.com/65517973/222789655-f5852f8f-f1e8-4676-8fb6-fe10b24f95da.png)

2023-03-03 17:37 UTC, vLuckyyy commented on src/components/projects/Projects.vue
> +          description="♾️ All the most important server functions in one! Made with love by EternalCodeTeam ❤️"
Przywróc poprzednią wersje bez "Made with love by eternalcodeteam"

2023-03-09 10:49 UTC, Osnixer approved these changes
Wszystko jest okej tylko nadal nie rozumiem czemu usuwamy z listy projektów "projekty nieaktywne" moim skromnym zdaniem tam powinny znajdować się wszystkie zrobione przez nas projekty.

2023-03-09 13:05 UTC, Embrejs commented
Może dodać sekcje wygasłych projektów tylko nazwać je: nieaktywne / wygasłe/ outdated / depricated

2023-03-10 16:51 UTC, Jakubk15 commented
Kompletnie "nie siedzą" mi nowe ikony, szczerze stare były lepsze, ale to moje zdanie. Kolejna sprawa to te kafelki z projektami, mogły być mniejsze imo, a napis "Nasze projekty" może mieć odstęp między podtekstem.

2023-03-10 16:53 UTC, Jakubk15 commented
W sensie, sugerowałbym zmniejszenie mocy tego glowu, może usunięcie tych okrągłych obramówek?

2023-03-10 18:44 UTC, closed without merging