setup type safe script and use routing
EternalCodeTeam/EternalCode-WWW pull request #86
Opened 2023-04-22 16:46 UTC by vLuckyyy

2023-04-22 18:11 UTC, Jakubk15 approved these changes
Możesz dodać także Prettiera

2023-04-22 20:07 UTC, Rollczi requested changes
Nie usuwaj przycisków z navbaru

2023-04-22 22:25 UTC, vLuckyyy commented
> Nie usuwaj przycisków z navbaru

Vue rotuer na chwilę obecną ma problem z hyperlinkami do **konkretnej** sekcji, więc uznałem że mozna je usunąć ponieważ są zbędne i do niczego nie prowadzą. 

Jeżeli uważasz że tak nie powinno być, proszę daj mi rozwiązanie na mój problem

ps. jak teraz nie usune to i tak to zrobie, prędzej czy później 🤣 (refactor navbaru)
![image](https://user-images.githubusercontent.com/65517973/233810278-f7621bb7-5171-4d15-99b2-5ca11cee5574.png)

2023-04-22 22:56 UTC, Kamicjusz reviewed
nie umiem w strony, ale buja :+1:

2023-04-23 15:46 UTC, Rollczi approved these changes

2023-04-23 15:47 UTC, merged